apiVersion: v1
kind: Secret
metadata:
  labels:
    app: spin
    cluster: spin-clouddriver
  name: spin-clouddriver-config
type: Opaque
stringData:
  clouddriver.yml: |
    spectator:
      applicationName: ${spring.application.name}
      webEndpoint:
        enabled: false
    
    server:
      port: ${services.clouddriver.port:7002}
      address: ${services.clouddriver.host:localhost}
    
    spinnaker:
      extensibility:
        plugins: {}
        repositories: {}
        plugins-root-path: /opt/clouddriver/plugins
        strict-plugin-loading: false
{{ tpl (toYaml .Values.clouddriver) . | indent 4 }}

  spinnaker.yml: |
    {{- tpl (.Files.Get "config/clouddriver/spinnaker.yml") . | nindent 4 }}
{{- if .Values.dynamicAccounts }}
  spinnakerconfig.yml: |
{{ tpl (toYaml .Values.dynamicAccounts) . | indent 4 }}
{{- else }}
  spinnakerconfig.yml: ""
{{- end }}
