apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    agent.opsmx.com/name: agent1
    agent.opsmx.com/role: agent
  name: opsmx-services-opsmx-agent
data:
  services.yaml: |
    outgoingServices:
      - name: agent-clouddriver
        type: clouddriver
        enabled: true
        config:
          url: http://spin-clouddriver:7002
      - name: demo-cluster
        type: kubernetes
        enabled: true
        namespaces:
        - name: test
          namespaces:
            - ninja-1
            - ninja-2
        - name: dev
          namespaces:
            - ninja-3
            - ninja-4
    incomingServices:
      - name: front50
        serviceType: front50
        port: 8080
        destination: controller
        destinationService: front50
      - name: fiat
        serviceType: fiat
        port: 7003
        destination: controller
        destinationService: fiat
