######################################################################
######################################################################
# Example config for the agent
# Credential can be give for services as a secret containing 
# keys "username" and "password"
# 
######################################################################
######################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  ########################################################################
  ########################################################################
  name: opsmx-services-demo-agent  ## REPLACE "demo-agent" agent-name
  ########################################################################
  ########################################################################
  labels:
    agent.opsmx.com/name: agent1
    agent.opsmx.com/role: agent
data:
  services.yaml: |
    outgoingServices:
      - name: dev-jenkins
        type: jenkins
        enabled: true
        config:
          url: https://dev-jenkins.opsmx.com
          credentials:
            type: basic
            secretName: jenkpass # k create secret generic jenkpass --from-literal username=UU --from-literal password=PP
      - name: dev-jen-inline-pass
        type: jenkins
        enabled: true
        config:
          url: http://jenkins.opsmx.net/jenkins/
          #credentials:
          #  type: basic
          #  username: b3BbkZXY=   # Base64 encoded
          #  password: QnVYlYmVlQDEyMyQ=
      - name: dev-artifactory
        type: artifactory
        enabled: true
        config:
          url: https://artifactory.example.com/
          repo: example-repo-local
          credentials:
            type: basic
            secretName: opsmx-artifactory
      - name: dev-bitbucket
        type: bitbucket
        enabled: true
        config:
          url: https://bitbucket.org/
          credentials:
            type: basic
            secretName: opsmx-bitbucket
